- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- init-container.py
> Issue 1.dockter.2

- docker-compose.test.yml
> issue-1 Update for RPM installation

- CHANGELOG.md
- Dockerfile
- init-container.py
> Issue 1.dockter.3

- CHANGELOG.md
- Dockerfile
- README.md
> issue-1 Make non-root container

- README.md
> Issue 1.dockter.5

- Dockerfile
- README.md
> issue-1 change to data/1.0

- README.md
> issue-1 Fix data version to data/1.0.0

- init-container.py
> issue-1 Removed TranslateG2ModuleException

- CHANGELOG.md
- init-container.py
> issue-16 Adjust for 1.12.0

- init-container.py
> issue-18 Cast string as int

- CHANGELOG.md
- Dockerfile
- README.md
- docs/debian-based-installation.md
- docs/rpm-based-installation.md
- init-container.py
- src/apt-packages.txt
- src/yum-packages.txt
> issue-22 Remove requirement for root user

- .dockerignore
- PULL_REQUEST_TEMPLATE.md
- README.md
> issue-21 Refactor to template

- Makefile
- README.md
> issue-27 Refactor to template

- init-container.py
> issue-26 Remove file manipulation from 'initialize-database' subcommand

- init-container.py
> issue-26 Add update-database-url subcommand

- init-container.py
> issue-26 Change subcommand parameters

- init-container.py
> #26 Determine if directory exists

- init-container.py
> #26 Fixed typo

- CHANGELOG.md
> #26 Prepare for release

- docs/README.md
- init-container.py
> #27 Refactor to template

- CHANGELOG.md
- init-container.py
> issue-36 Create G2C_LIBFEAT.db and G2C_RES.db

- CHANGELOG.md
> #36 Prepare for Release

- CHANGELOG.md
- Dockerfile
> #39 Update to senzing/senzing-base:1.4.0

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #41 
change the git action hook
accurate git action hooks
> Issue 41.mahchiahui.1

- init-container.py
> #48 Restructure logic

- init-container.py
> #36 Add support for SENZING_ENGINE_CONFIGURATION_JSON

- CHANGELOG.md
- Makefile
- README.md
- init-container.py
- src/apt-packages.txt
> issue-51 Improve documentation and logging

- .github/ISSUE_TEMPLATE/documentation_request.md
- README.md
> #51 Prepare for version

- CHANGELOG.md
- init-container.py
> issue-54 Adjust code to account for changes in Senzing SDK

- CHANGELOG.md
- Dockerfile
- init-container.py
> #59 Add PostgreSQL ODBC support

- CHANGELOG.md
- init-container.py
> Issue 62.dockter.1

- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #64 
fixing tool chain breakage
> fixing ci/cd tool chain reference to gitactions

- CHANGELOG.md
- Dockerfile
- init-container.py
> #66 Update to senzing/senzing-base:1.5.1

- .github/workflows/cd-pr-test-debian-build.yml
- Dockerfile
- Makefile
> Issue 68.macy.1

- CHANGELOG.md
> #68 upgrade to senzing/senzing-base:1.5.2

- CHANGELOG.md
- init-container.py
- rootfs/etc/odbc.ini.mssql-template
> Issue 72.dockter.1

- CHANGELOG.md
- init-container.py
> #73 Changed permission on db2dsdriver.cfg to 755

- CHANGELOG.md
Issue number: #77 
Changelog update
> Update CHANGELOG.md for 1.5.9

- CHANGELOG.md
Issue number: #77 
Adding to changelog
> One more item for the changelog for 1.5.8

- init-container.py
> migrate from 16-2debian9 to 20-1debian10

- CHANGELOG.md
- init-container.py
> Issue 75.dockter.1

- CHANGELOG.md
- init-container.py
> Issue 86.dockter.1

- init-container.py
Issue number: #88 
The governor was not being automatically installed like it should. This is a workaround until #89 is fixed.
> Issue 88.jadair.1

- CHANGELOG.md
> Update CHANGELOG.md for 1.6.1

- init-container.py
> #92 Add support for SENZING_LICENSE_BASE64_ENCODED

- init-container.py
> #92 Fix internal version

- CHANGELOG.md
- init-container.py
> #89 Add support for SENZING_GOVERNOR_URL

- init-container.py
- rootfs/etc/odbc.ini.mssql-template
Issue number: #89 
db specific init was not getting run so clusters would not work with some db types
???
> Calling db specific initialization for clustered configs

- CHANGELOG.md
> Update changelog.md for 1.6.4

- CHANGELOG.md
- Dockerfile
- Makefile
- init-container.py
> Issue 107.dockter.1

- CHANGELOG.md
- Dockerfile
- init-container.py
> #107  Refactored code

- CHANGELOG.md
> Changelog updated for 1.6.9

- CHANGELOG.md
- init-container.py
> Issue 114.dockter.1

- README.md
> #116 Update to senzingdata 2.0.0

- init-container.py
> REDACT senzing_engine_configuration_json

- .dockerignore
- CHANGELOG.md
- Dockerfile
> 119 update base senzing version

- CHANGELOG.md
- Dockerfile
> #121 updated to senzing base 1.6.1

- init-container.py
Issue number: #130 
required for senzing api server mtls authentication
allow users to add in their own java keystores
> #130 added server and client keystore base64 parsing

- CHANGELOG.md
- Dockerfile
- init-container.py
> #130 Prepare for versioned release

- CHANGELOG.md
- Dockerfile
> Issue 137.ron.0 update base image

- CHANGELOG.md
- Dockerfile
- init-container.py
> Issue 128.dockter.5

- CHANGELOG.md
- Dockerfile
- init-container.py
> Issue 143.dockter.1

- CHANGELOG.md
- Dockerfile
- init-container.py
Issue number: #145 
version update
> #145 version update

- CHANGELOG.md
- Dockerfile
> #142 Add libodbc1

- README.md
- rootfs/etc/odbc.ini.mssql-template
> Issue 151.dockter.1

- CHANGELOG.md
- Dockerfile
- init-container.py
> #160 Add debug information on entry

- CHANGELOG.md
- init-container.py
> Issue 166.dockter.1

- CHANGELOG.md
- Dockerfile
- README.md
- docs/debian-based-installation.md
- docs/rpm-based-installation.md
- init-container.py
> Issue 170.dockter.1

- .github/CODEOWNERS
- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- .github/workflows/add-triage-label.yaml
- .github/workflows/build-docker-container.yaml
- .github/workflows/identify-customer.yaml
- .github/workflows/pylint.yaml
> #181 Modify workflows

- CHANGELOG.md
- Dockerfile
- init-container.py
> #184 Prepare for versioned release

- CHANGELOG.md
- Dockerfile
- init-container.py
Update underlying docker images.
Issue number: #1
> github-util: Update FROM version

- CHANGELOG.md
- README.md
> #324 Update links

- README.md
- docs/development.md
- docs/errors.md
- docs/examples.md
> #332 Savepoint
